### ISSUE TITLE
MobaXterm on linux

### ISSUE THREAD

**Issue by ProductionEXP** [F1r3w477/my-tutorials#5]
In this guide https://github.com/F1r3w477/my-tutorials/blob/main/Valheim%20Dedicated%20VPS%20-%20HyperExpert/README.md you recommend MobaXterm which can not be run on Linux as this is the Linux guide you might want to change this.

**Comment by F1r3w477** [comment]
The guide is not a Linux guide. The guide is walking users through interacting with a Linux VPS via their preferred SSH tool. I recommend MobaXterm as I use it from my windows machine. There is no pre-requisite set in the guide to be running windows, so removing MobaXterm wouldn't be beneficial. 

I will, however, update the guide to reflect that MobaXterm is not available for install on a Linux machine.

**Comment by F1r3w477** [comment]
[52955fe](https://github.com/F1r3w477/my-tutorials/commit/52955fe11c3fd59cbba553c16df4a9d14b8668ba)
